name: Keep Backend Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Backend Health Check
      run: |
        echo "Pinging backend health check..."
        response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 https://secure-vm-portal-backend.onrender.com/api/health)
        
        if [ $response -eq 200 ]; then
          echo "✅ Backend is alive (HTTP $response)"
        else
          echo "❌ Backend ping failed (HTTP $response)"
          exit 1
        fi
    
    - name: Log Status
      run: |
        echo "Backend keep-alive check completed at $(date)"